//these numbers are added on to already existing ones

const attack_patterns = {
	"1": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":20,"damage":200},
		],
		"skill_critical":[
			{"probability":20,"damage":200},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"3": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":4,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":20,"damage":200},
		],
		"skill_critical":[
			{"probability":20,"damage":200},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"4": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"5": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"6": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"7": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":-2,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"8": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"11": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"12": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"13": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"14": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"15": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":5000,"extraTarget":0,"extraMulti":4,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"16": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"17": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"19": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10019": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"20": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"21": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"22": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10022": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"23": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"24": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10024": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"25": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10025": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"26": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"27": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":70,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
				{"probability":30,"time":3000,"extraTarget":2,"extraMulti":0,"text":"特殊攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":3000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"27a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":60,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
				{"probability":40,"time":3000,"extraTarget":2,"extraMulti":0,"text":"特殊攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":3000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"28": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"29": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"30": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10030": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"31": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"32": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10032": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"33": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"34": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"35": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"36": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4500,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"37": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"38": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10038": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"39": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10039": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"40": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"41": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":5000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"42": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"43": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"44": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":40,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
				{"probability":24,"time":6000,"extraTarget":0,"extraMulti":0,"text":"2回攻撃"},
				{"probability":36,"time":8000,"extraTarget":0,"extraMulti":0,"text":"3回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10044": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":40,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
				{"probability":24,"time":6000,"extraTarget":0,"extraMulti":0,"text":"2回攻撃"},
				{"probability":36,"time":8000,"extraTarget":0,"extraMulti":0,"text":"3回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"46": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10046": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"47": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"49": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"50": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"51": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":50,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1体攻撃"},
				{"probability":50,"time":4000,"extraTarget":1,"extraMulti":0,"text":"2体攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":50,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル1体攻撃"},
				{"probability":50,"time":4000,"extraTarget":1,"extraMulti":1,"text":"スキル2体攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"51a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":40,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1体攻撃"},
				{"probability":60,"time":4000,"extraTarget":1,"extraMulti":0,"text":"2体攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":40,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル1体攻撃"},
				{"probability":60,"time":4000,"extraTarget":1,"extraMulti":1,"text":"スキル2体攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"52": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"53": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"54": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"55": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"56": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"}, 
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"57": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"58": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10058": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"59": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"60": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10060": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"61": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":0.5,"text":"ターゲット"},
				{"probability":100,"time":6000,"extraTarget":98,"extraMulti":3.5,"text":"火の輪(範囲内計算)"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"62": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"63": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10063": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"64": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":3,"text":"スキル攻撃"},
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
				{"probability":33.34,"time":2500,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":3,"text":"スキル攻撃"},
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
				{"probability":33.34,"time":2500,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
				{"probability":33.33,"time":2500,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
				{"probability":33.34,"time":2500,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":2500,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"65": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10065": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"66": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":50,"damage":200},
		],
		"skill_critical":[
			{"probability":100,"damage":200},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"66a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":50,"damage":230},
		],
		"skill_critical":[
			{"probability":100,"damage":230},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"67": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"68": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"69": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"70": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"71": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":98,"extraMulti":4,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"72": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"73": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"74": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"75": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"76": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"77": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"78": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10078": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":4,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"79": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"80": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"81": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"82": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"83": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":5500,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"84": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"85": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10085": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":1,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"86": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"87": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"88": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"10088": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"89": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"90": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"91": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":10000,"extraTarget":0,"extraMulti":9,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"92": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"93": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"94": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":70,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
				{"probability":30,"time":3000,"extraTarget":0,"extraMulti":2,"text":"特殊攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":3000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[50],
		"skill_penetration":[50],
		"BCL":0,
		"SCL":0,
		"BPL":1,
		"SPL":1,
	},
	"94a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":60,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
				{"probability":40,"time":3000,"extraTarget":0,"extraMulti":2,"text":"特殊攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":3000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[50],
		"skill_penetration":[50],
		"BCL":0,
		"SCL":0,
		"BPL":1,
		"SPL":1,
	},
	"95": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"96": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"97": {
		"attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":25,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
				{"probability":18.75,"time":6000,"extraTarget":0,"extraMulti":1,"text":"2回攻撃"},
				{"probability":14.06,"time":8000,"extraTarget":0,"extraMulti":2,"text":"3回攻撃"},
				{"probability":10.55,"time":10000,"extraTarget":0,"extraMulti":3,"text":"4回攻撃"},
				{"probability":31.64,"time":12000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"97a": {
		"attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":25,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
				{"probability":18.75,"time":6000,"extraTarget":0,"extraMulti":1,"text":"2回攻撃"},
				{"probability":14.06,"time":8000,"extraTarget":0,"extraMulti":2,"text":"3回攻撃"},
				{"probability":10.55,"time":10000,"extraTarget":0,"extraMulti":3,"text":"4回攻撃"},
				{"probability":31.64,"time":12000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"1回攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"98": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"99": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"100": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"101": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":8000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"103": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"104": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"106": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"107": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"111": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"112": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"113": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"114": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"115": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"116": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"119": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"120": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"121": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"123": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"125": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"126": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"127": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"132": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"134": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"135": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"136": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":1,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"137": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"138": {
		"attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"斧攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"ミサイル攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1","",1]],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":0,"text":"斧攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":2,"text":"ミサイル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"139": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"140": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":25,"damage":200},
		],
		"skill_critical":[
			{"probability":25,"damage":200},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"140a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃"},
			]},
		],
		"critical":[
			{"probability":30,"damage":200},
		],
		"skill_critical":[
			{"probability":30,"damage":200},
		],
		"penetration":[],
		"skill_penetration":[],
		"BCL":1,
		"SCL":1,
		"BPL":0,
		"SPL":0,
	},
	"141": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"143": {
		"attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[["condition","1007","",13014]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13013]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":2,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[["condition","1007","",13012]],
			"pattern":[
				{"probability":33.33,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃(弓)"},
				{"probability":66.67,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"145": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"146": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":60,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
				{"probability":40,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"146a": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":48,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
				{"probability":52,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":4,"text":"5回攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"147": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"148": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":-1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":6000,"extraTarget":0,"extraMulti":-1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"149": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"150": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":1,"extraMulti":2,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"151": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"152": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"回復"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル回復"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"158": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"161": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"164": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":75,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
				{"probability":25,"time":4000,"extraTarget":2,"extraMulti":0,"text":"特殊攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"165": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":1,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"177": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
	"178": {
		"attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"攻撃"},
			]},
		],
		"skill_attack":[
			{"cond":[],
			"pattern":[
				{"probability":100,"time":4000,"extraTarget":0,"extraMulti":0,"text":"スキル攻撃"},
			]},
		],
		"critical":[],
		"skill_critical":[],
		"penetration":[],
		"skill_penetration":[],
		"BCL":0,
		"SCL":0,
		"BPL":0,
		"SPL":0,
	},
}