//these numbers are added on to already existing ones

const continuous_patterns = {
	"0": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"target":"none",
		"time":30,
	},
	"40": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":15},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":15},
		},
		"target":"special",
		"time":60,
	},
	"49": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":3},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":15},
		},
		"target":"range",
		"time":30,
	},
	"49a": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":4},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":20},
		},
		"target":"range",
		"time":30,
	},
	"63": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"target":"block",
		"time":15,
	},
	"63a": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"target":"block",
		"time":15,
	},
	"10063": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"block",
		"time":15,
	},
	"10063a": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":10},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"block",
		"time":15,
	},
	"67": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":80},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":80},
		},
		"target":"target",
		"time":"attack",
	},
	"92": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":3},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":9},
		},
		"target":"range",
		"time":30,
	},
	"92a": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":4},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":12},
		},
		"target":"range",
		"time":30,
	},
	"136-1": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136-2": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136-3": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136-4": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136-5": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136a-1": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136a-2": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136a-3": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136a-4": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"136a-5": {
		"battle":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":0},
		},
		"skill":{
			"cond":[],
			"damage":{"hitType":"貫通","reference":"stat2","multiplier":40},
		},
		"target":"range",
		"time":30,
	},
	"145": {
		"battle":{
			"cond":[["condition","2","",1]],
			"damage":{"hitType":"魔法","reference":"stat2","multiplier":30},
		},
		"skill":{
			"cond":[["condition","2","",1]],
			"damage":{"hitType":"魔法","reference":"stat2","multiplier":35},
		},
		"target":"range",
		"time":60,
	},
	"145a": {
		"battle":{
			"cond":[["condition","2","",1]],
			"damage":{"hitType":"魔法","reference":"stat2","multiplier":30},
		},
		"skill":{
			"cond":[["condition","2","",1]],
			"damage":{"hitType":"魔法","reference":"stat2","multiplier":35},
		},
		"target":"range",
		"time":60,
	},
}