document.write(`
<style>
#subskill-select-div-2{
    display:none;
    position:absolute;
    height:95%;
    width:95%;
    left: 2.5%;
    top: 2.5%;
    background-color: white;
    border-radius: 5px;
    border: 2px solid black;
    overflow: auto;
    opacity: 97%;
}
#subskill-select-search-2{
    position:sticky;
    width: 99.9%;
    top:0;
    background-color: #ffb8c3;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    border-bottom-left-radius: 5px;
    border-bottom-right-radius: 5px;
    border: 1px solid black;
    font-size: 1.5vw;
}
.subskill-select-flex-container{
    display: flex;
    flex-wrap: wrap;
}
.subskill-select-img-2{
    width:33%;
    cursor:pointer;
}
</style>
<div id="subskill-select-div-2">
    <div id="subskill-select-search-2">
        <table>
            <tr>
                <td style="font-family:mtdfont;">サブスキル検索</td>
                <td>
                    <input type="search" id="subskill-searchbox-2" style="margin:3px;font-size:1.2vw;font-family:mtdfont;" oninput="subskillSearch('2');">
                </td>
                <td style="text-align:right;">
                    <button onclick="subskillSearchSelect('_0.','2');subskillSearchClose();allDPS();" style="border-radius:5px;background-color:#edd58f;font-size:1.5vw;font-family:mtdfont;cursor:pointer;">はずす</button>
                </td>
            </tr>
        </table>    
    </div>
    <div class="subskill-select-flex-container">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1001.png"
        alt="HP強化 I-HPきょうかいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1002.png"
        alt="HP強化 II-HPきょうかに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1003.png"
        alt="HP強化 III-HPきょうかさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1004.png"
        alt="攻撃力強化 I-こうげきりょくきょうかいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1005.png"
        alt="攻撃力強化 II-こうげきりょくきょうかに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1006.png"
        alt="攻撃力強化 III-こうげきりょくきょうかさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1007.png"
        alt="物理防御強化 I-ぶつりぼうぎょきょうかいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1008.png"
        alt="物理防御強化 II-ぶつりぼうぎょきょうかに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1009.png"
        alt="物理防御強化 III-ぶつりぼうぎょきょうかさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1010.png"
        alt="魔法防御強化 I-まほうぼうぎょきょうかいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1011.png"
        alt="魔法防御強化 II-まほうぼうぎょきょうかに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1012.png"
        alt="魔法防御強化 III-まほうぼうぎょきょうかさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1013.png"
        alt="リジェネレーション I-りじぇねれーしょんいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1014.png"
        alt="リジェネレーション II-りじぇねれーしょんに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1015.png"
        alt="リジェネレーション III-りじぇねれーしょんさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1016.png"
        alt="物理攻撃回避 I-ぶつりこうげきかいひいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1017.png"
        alt="物理攻撃回避 II-ぶつりこうげきかいひに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1018.png"
        alt="物理攻撃回避 III-ぶつりこうげきかいひさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1019.png"
        alt="魔法攻撃回避 III-まほうこうげきかいひいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1020.png"
        alt="魔法攻撃回避 III-まほうこうげきかいひに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1021.png"
        alt="魔法攻撃回避 III-まほうこうげきかいひさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1022.png"
        alt="移動速度上昇 I-いどうそくどじょうしょういち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1023.png"
        alt="移動速度上昇 II-いどうそくどじょうしょうに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1024.png"
        alt="移動速度上昇 III-いどうそくどじょうしょうさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1025.png"
        alt="クリティカル I-くりてぃかるいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1026.png"
        alt="クリティカル II-くりてぃかるに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1027.png"
        alt="クリティカル III-くりてぃかるさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1028.png"
        alt="再出撃時間短縮 I-さいしゅつげきじかんたんしゅくいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1029.png"
        alt="再出撃時間短縮 II-さいしゅつげきじかんたんしゅくに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1030.png"
        alt="再出撃時間短縮 III-さいしゅつげきじかんたんしゅくさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1031.png"
        alt="生命力吸収 I-せいめいりょくきゅうしゅういち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1032.png"
        alt="生命力吸収 II-せいめいりょくきゅうしゅうに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1033.png"
        alt="生命力吸収 III-せいめいりょくきゅうしゅうさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1034.png"
        alt="攻撃待機時間短縮 I-こうげきたいきじかんたんしゅくいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1035.png"
        alt="攻撃待機時間短縮 II-こうげきたいきじかんたんしゅくに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1036.png"
        alt="攻撃待機時間短縮 III-こうげきたいきじかんたんしゅくさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1037.png"
        alt="貫通攻撃 I-かんつうこうげきいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1038.png"
        alt="貫通攻撃 II-かんつうこうげきに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1039.png"
        alt="貫通攻撃 III-かんつうこうげきさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1040.png"
        alt="底力(攻撃) I-そこぢからこうげきいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1041.png"
        alt="底力(攻撃) II-そこぢからこうげきに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1042.png"
        alt="底力(攻撃) III-そこぢからこうげきさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1043.png"
        alt="底力(物理防御) I-そこぢからぶつりぼうぎょいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1044.png"
        alt="底力(物理防御) II-そこぢからぶつりぼうぎょに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1045.png"
        alt="底力(物理防御) III-そこぢからぶつりぼうぎょさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1046.png"
        alt="撤退時コスト回復 I-てったいじこすとかいふくいち"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1047.png"
        alt="撤退時コスト回復 II-てったいじこすとかいふくに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1048.png"
        alt="撤退時コスト回復 III-てったいじこすとかいふくさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1049.png"
        alt="アイアンボディ-あいあんぼでぃ-物理ダメージを25%減少-ぶつりだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1050.png"
        alt="ファストチャージャー-ふぁすとちゃーじゃー-スキル使用後、再発動までの時間を3秒短くする-再使用-さいしよう-さいはつどう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1051.png"
        alt="オートパニッシャー-おーとぱにっしゃー-敵の攻撃力の10％を反射しダメージを与える-はんしゃ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1052.png"
        alt="エレメンタルブースト-えれめんたるぶーすと-同属性マスに配置したボーナスが1.5倍"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1053.png"
        alt="フェニックスの加護-ふぇにっくすのかご-HPが1秒ごとに45回復し、再出撃時間を40%短縮再出撃時間短縮は重複不可-リジェネレーション-りじぇねれーしょん-さいしゅつげき"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1054.png"
        alt="騎士の心得-きしのこころえ-物理防御+15％、ガーディアン系クラスにセット時追加でHP+500-ぶつりぼうぎょ-がーでぃあん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1055.png"
        alt="霧を晴らす列車-きりをはらすれっしゃ-移動速度+40％、移動消費コスト-1-いどうそくど"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1056.png"
        alt="巨鎧騎士の討伐証-きょがいきしのとうばつしょう-最大HP+650、斧装備クラスにセット時追加で攻撃力+100-おの-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1057.png"
        alt="攻撃+物理防御強化-こうげきぶつりぼうぎょきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1058.png"
        alt="黄金岩晶の討伐証-おうごんがんしょうのとうばつしょう-移動速度+60％、剣装備クラスにセット時追加で物理防御+100-いどうそくど-つるぎ-けん-ぶつりぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1059.png"
        alt="フルハートハイビート-ふるはーとはいびーと-HPが最大状態の時、4秒毎にスキル準備時間-1秒-すきる-さいはつどう-さいしよう-再発動-再使用"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1060.png"
        alt="双角王者の討伐証-そうかくおうじゃのとうばつしょう-物理防御+40、オーブ装備クラスにセット時追加で魔法防御+40-ぶつりぼうぎょ-おーぶ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1061.png"
        alt="純白ヴェール-じゅんぱくゔぇーる-魔法防御力+40、魔法ダメージを5％減少-まほうぼうぎょ-まほうだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1062.png"
        alt="冥途の置き土産-めいどのおきみやげ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1063.png"
        alt="捨て身の一撃-すてみのいちげき-与ダメージが1.2倍になるが、攻撃ヒット時に最大HP3％の反動ダメージを受ける-よだめーじ-はんどう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1064.png"
        alt="攻撃+魔法防御強化-こうげきまほうぼうぎょきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1065.png"
        alt="HP+物理防御強化-えいちぴーぶつりぼうぎょきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1066.png"
        alt="HP+魔法防御強化-えいちぴーまほうぼうぎょきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1067.png"
        alt="聖なる祈り-せいなるいのり-スキル使用後10秒間、全味方(トークン含)のHPを1秒ごとに75回復させる-すきる-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1068.png"
        alt="物理防御+魔法防御強化-ぶつりぼうぎょまほうぼうぎょきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1069.png"
        alt="HP強化+出撃コスト減少-えいちぴーきょうかしゅつげきこすとげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1070.png"
        alt="竜騎士の討伐証-りゅうきしのとうばつしょう-最大HP+650、扇装備クラスにセット時追加で攻撃力+80-せんす-うちわ-おうぎ-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1071.png"
        alt="結石竜の討伐証-けっせきりゅうのとうばつしょう-攻撃力+17％、石化状態の敵に与えるダメージ1.1倍-こうげきりょく-せっか-せきか-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1072.png"
        alt="スタートチャージャー-すたーとちゃーじゃー-スキル初回使用までの時間を10秒短くする-しょかいしよう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1073.png"
        alt="魔導の心得-まどうのこころえ-攻撃力+12%、ソーサラー系クラスにセット時追加で射程+10-こうげきりょく-そーさらー-しゃてい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1074.png"
        alt="リミットブレイク-りみっとぶれいく-スキル中与ダメージが1.3倍になるが、スキル終了時最大HP60%の反動ダメージ-すきる-よだめーじ-はんどう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1075.png"
        alt="ゴブリンパーティ！-ごぶりんぱーてぃ-トークン-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1076.png"
        alt="高貴なる狩人-こうきなるかりうど-攻撃力+12%、スナイパー系クラスにセット時追加で射程+5-こうげきりょく-すないぱー-しゃてい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1077.png"
        alt="魔導艦の討伐証-まどうかんのとうばつしょう-最大HP+650、鈍器装備クラスにセット時追加で攻撃力+120-どんき-こん棒-こんぼう-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1078.png"
        alt="攻撃強化+出撃コスト減少-こうげききょうかしゅつげきこすとげんしょう-"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1079.png"
        alt="物理防御強化+物理攻撃回避"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1080.png"
        alt="古代艦の討伐証-こだいかんのとうばつしょう-最大HP+600、槍装備クラスにセット時追加で攻撃力+100-やり-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1081.png"
        alt="攻撃強化+リジェネレーション-こうげききょうかりじぇねれーしょん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1082.png"
        alt="皇女の誇り-おうじょのほこり-攻撃力+17％、ヒーラー系クラスにセット時追加で攻撃力+70-こうげきりょく-ひーらー"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1083.png"
        alt="ぐねぐねスライムくん（緑）-ぐねぐねすらいくんむみどり-トークン-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1084.png"
        alt="タクティクスガード-たくてぃくすがーど-配置中、全味方の物理防御力+4%-はいち-ぜんみかた-ぶつりぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1085.png"
        alt="物理防御強化+出撃コスト減少-ぶつりぼうぎょきょうかしゅつげきこすとげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1086.png"
        alt="常夏巨兵の討伐証-とこなつきょへいのとうばつしょう-最大HP+650、剣装備クラスにセット時追加で物理防御+120-つるぎ-けん-ぶつりぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1087.png"
        alt="攻撃強化+貫通攻撃-こうげききょうかかんつうこうげき"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1088.png"
        alt="生命力吸収+攻撃待機短縮-せいめいりょくきゅうしゅうこうげきたいきたんしゅく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1089.png"
        alt="まったり充電寝正月-まったりじゅうでんねしょうがつ-非スキル中通常の攻撃を行わなくなるが-秒毎にスキル準備時間-1秒-(サポーター系クラスは効果の対象外)-ひすきる-再使用-再発動-さいはつどう-さいしよう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1090.png"
        alt="疾風怒濤-しっぷうどとう-移動中、攻撃力+100%-いどうちゅう-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1091.png"
        alt="先手必勝！-せんてひっしょう-配置してから30秒間、与ダメージ1.5倍-はいち-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1092.png"
        alt="ポイズンボム-ぽいずんぼむ-配置時に周囲の敵に攻撃力2.5倍のダメージを与え、高確率で猛毒状態にする"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1093.png"
        alt="HP強化+リジェネレーション-えいちぴーきょうかりじぇねれーしょん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1094.png"
        alt="物理攻撃+魔法攻撃回避"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1095.png"
        alt="41ストーン-じいすとーん-HP+0721\r\n物理防御力+45、魔法防御力+45-ぶつりぼうぎょ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1096.png"
        alt="究極機将の討伐証-きゅうきょくきしょうのとうばつしょう-攻撃力15％、斧装備クラスにセット時追加で物理防御力+120-こうげきりょく-おの-ぶつりぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1097.png"
        alt="穴鏡触手の討伐証-けっきょうしょくしゅのとうばつしょう-敵の攻撃力の8％を反射しダメージを与える\r\n剣装備クラスにセット時追加で物防魔防+30-はんしゃ-つるぎ-けん-ぶつりぼうぎょ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1098.png"
        alt="1st Anniversaryの祝福-ふぁーすとあにばーさりーのしゅくふく-HP+1111、攻撃力+111\r\n物理防御力+111、魔法防御力+111-こうげきりょく-ぶつりぼうぎょ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1099.png"
        alt="プロトバリア-ぷろとばりあ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1100.png"
        alt="アタッチヒール-あたっちひーる-スキル発動時、自身のHPを20%回復-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1101.png"
        alt="屍山血河-しざんけつが-ちいかわ-敵を攻撃で倒すごとに攻撃力が1%上昇-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1102.png"
        alt="攻撃強化+クリティカル-こうげききょうかくりてぃかる"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1103.png"
        alt="恩愛触手の討伐証-おんあいしょくしゅのとうばつしょう-魔法防御力+100、本装備クラスにセット時追加で攻撃力+100-まほうぼうぎょ-ほん-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1104.png"
        alt="暗躍する影-あんやくするかげ-攻撃力+15％、短剣装備クラスにセット時追加で背後からの攻撃時与ダメージ1.2倍-こうげきりょく-たんけん-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1105.png"
        alt="HP強化 IV-えいちぴーきょうかよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1106.png"
        alt="攻撃力強化 IV-こうげきりょくきょうかよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1107.png"
        alt="物理防御強化 IV-ぶつりぼうぎょきょうかよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1108.png"
        alt="魔法防御強化 IV-まほうぼうぎょきょうかよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1109.png"
        alt="ポイズンエンチャント-ぽいずんえんちゃんと-攻撃時、低確率で毒を付与\r\n毒状態の敵へ与ダメージ1.2倍-どく-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1110.png"
        alt="ガードプロテクト-がーどぷろてくと-配置中、全味方が受ける物理ダメージ15%減少-はいち-ぜんみかた-ぶつりだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1111.png"
        alt="パワフルリジェネ-ぱわふるりじぇね-HPが1秒ごとに60回復する\r\nスキル発動後10秒間回復量3倍-すきる-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1112.png"
        alt="オールレジスト-おーるれじすと-毒、石化、スタン耐性+50-どく-せっか-せきか-すたん-たいせい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1113.png"
        alt="アサルトチャージ-あさるとちゃーじ-移動中、攻撃力+120％\r\n移動速度+100-いどうちゅう-いどうそくど-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1114.png"
        alt="MAXマッスル-まっくすまっする-HPが100%以上の時与ダメージ1.3倍-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1115.png"
        alt="きらめきの星騎士-きらめきのせいきし-魔法ダメージを5%軽減\r\n全味方のHPを1秒毎に15回復する-まほうだめーじげんしょう-けいげん-ぜんみかた-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1116.png"
        alt="触手も付けとくでぇ！-しょくしゅもつけとくでぇ-スキル発動時、被ダメージを半分肩代わりする触手トークンを自身のマスに召喚-とーくん-トークン-スキル-すきる"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1117.png"
        alt="ハイテンションサマー-はいてんしょんさまー-HPが80%以上の時、攻撃速度が上昇し攻撃後の待機時間50%減少-こうげきそくど-たいきじかんたんしゅく-たいきじかんげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1118.png"
        alt="灼熱噴然の討伐証-しゃくねつふんぜんのとうばつしょう-物理ダメージを5%軽減\r\n地属性ユニットにセット時追加で最大HP+700-ぶつりだめーじげんしょう-けいげん-ちぞくせい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1119.png"
        alt="テッパンツンデレ皇女-てっぱんつんでれおうじょ-セット時、全モンスター娘の攻撃力+5%\r\nカティナをトークンとして使役可能-とーくん-こうげきりょく-へんせい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1120.png"
        alt="おっとりお姉ちゃん皇女-おっとりおねえちゃんおうじょ-セット時、全モンスター娘の最大HP+10%\r\nリンデンハートをトークンとして使役可能-とーくん-へんせい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1121.png"
        alt="逆境の力-ぎゃっきょうのちから-HP50％以下の時、与ダメージが1.5倍-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1122.png"
        alt="マジックボディ-まじっくぼでぃ-魔法ダメージを25%減少-まほうだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1123.png"
        alt="魔法防御強化+魔法攻撃回避-まほうぼうぎょきょうかまほうこうげきかいひ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1124.png"
        alt="快適快速-かいてきかいそく-移動時物理、魔法攻撃を20％の確率で回避\r\n移動消費コスト-5-いどうじ-いどうちゅう-まほうこうげきかいひ-いどうこすと-いどうしょうひこすと"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1125.png"
        alt="グレイトコンダクト-ぐれいとこんだくと-自身の使役するトークンの\r\n与えるダメージが1.3倍-とーくん-よだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1126.png"
        alt="魔導傑作の討伐証-まどうけっさくのとうばつしょう-攻撃力+15%、杖クラス装備時射程+10-こうげきりょく-つえ-しゃてい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1127.png"
        alt="再出撃時間短縮 IV-さいしゅつげきじかんたんしゅくよん-"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1128.png"
        alt="貫通攻撃 IV-かんつうこうげきよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1129.png"
        alt="ラピッドチャージャー-らぴっどちゃーじゃー-スキル初回使用までの時間を4秒短くする\r\nスキル使用後、再発動までの時間を4秒短くする-すきるしょかいしよう-再使用-さいしよう-さいはつどう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1130.png"
        alt="ウィンドエクステンド-うぃんどえくすてんど-編成時風属性モンスター娘のHPと攻撃力+10%-へんせいじ-かぜぞくせい-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1131.png"
        alt="決死の一撃-けっしのいちげき-与ダメージが1.6倍になるが、\r\n攻撃ヒット時に最大HP10%の反動ダメージを受ける-よだめーじ-はんどう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1132.png"
        alt="メデューサソウル-めでゅーさそうる-石化、毒状態の敵への与ダメージ1.3倍\r\nメデューサ(原種)をトークンとして使役可能-せきか-せっか-どく-よだめーじ-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1133.png"
        alt="再出撃時間短縮+撤退時コスト回復-さいしゅつげきじかんたんしゅくてったいじこすとかいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1134.png"
        alt="麗しき藝術家-うるわしきげいじゅつか-配置時、マップ上のマスをランダムで\r\n火水風属性に変更する-はいち-ますへんこう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1135.png"
        alt="聖女の加護-せいじょのかご-HP+20%、錫杖装備クラスにセット時に追加で射程+10-しゃくじょう-しゃてい"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1136.png"
        alt="クリティカル+貫通攻撃-くりてぃかるかんつうこうげき"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1137.png"
        alt="1.5th Anniversaryの恩恵-わんはーふすあにばーさりーのおんけい-HP、攻撃力、防御力+15％\r\n再出撃までの時間を15%短縮-こうげきりょく-ぶつりぼうぎょ-まほうぼうぎょ-さいしゅつげきたんしゅく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1138.png"
        alt="怪幹呑獣の討伐証-かいかんどんじゅうのとうばつしょう-HP+650、霊枝装備クラスにセット時\r\nHPが1秒ごとに最大値の1%回復-えだ-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1139.png"
        alt="一級ご主人証明書-いっきゅうごしゅじんしょうめいしょ-HP、攻撃力+18％\r\n出撃コスト-2-こうげきりょく-しゅつげきこすと"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1140.png"
        alt="ライフブロック-らいふぶろっく-HP+15%、ブロックしている敵1体につき\r\n最大HP+8%"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1141.png"
        alt="タクティクスMガード-たくてぃくすえむがーど-配置中、全味方の魔法防御力+4%-ぜんみかた-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1143.png"
        alt="クリティカルダメージ強化 II-くりてぃかるだめーじきょうかに"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1142.png"
        alt="クリティカルダメージ強化 III-くりてぃかるだめーじきょうかさん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1144.png"
        alt="クリティカル+CRIダメージ強化-くりてぃかるくりてぃかるだめーじきょうか"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1145.png"
        alt="スキルエクステンド-すきるえくすてんど-非スキル中、攻撃力と防御力+15%\r\nスキル中、攻撃力と防御力+30%-ひすきる-こうげきりょく-ぶつりぼうぎょ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1146.png"
        alt="攻撃強化+生命力吸収-こうげききょうかせいめいりょくきゅうしゅう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1147.png"
        alt="クリティカル IV-くりてぃかるよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1148.png"
        alt="クリティカルダメージ強化 IV-くりてぃかるだめーじきょうかよん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1149.png"
        alt="マッスルチャレンジャー-まっするちゃれんじゃーHPが30%以上の時回復効果を受けられなくなるが、最大HP+60%-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1150.png"
        alt="オーバードーピング-おーばーどーぴんぐ-出撃コスト+10になるが\r\n攻撃力、物理防御、魔法防御+30%-しゅつげきこすと-こうげきりょく-ぶつりぼうぎょ-まほうぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1151.png"
        alt="ラッキーヒール-らっきーひーる-クリティカル時、全味方のHPを160回復-くりてぃかるじ-ぜんみかた-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1152.png"
        alt="ケルベロスソウル-けるべろすそうる-最大HP+33％\r\nケルベロス(闇原種)をトークンとして使役可能-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1153.png"
        alt="膨大巨嚢の討伐証-ぼうだいきょのうのとうばつしょう-攻撃力+15%、場から離れる時に爆発し、周囲の敵に攻撃力分のダメージ-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1154.png"
        alt="妖怪島探検家-ようかいじまたんけんか--攻撃力+17%、妖怪にセット時出撃コスト-2-こうげきりょく-しゅつげきこすと"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1155.png"
        alt="攻撃待機短縮+出撃コスト減少-こうげきたいきたんしゅくしゅつげきこすとげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1156.png"
        alt="来たる福女！-きたるふくおんな-クリティカル率+20％、移動速度+100\r\nクリティカル時、攻撃速度が10秒間10%増加-くりてぃかるりつ-くりてぃかるじ-いどうそくど-こうげきそくど"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1157.png"
        alt="煩悶淫竜の討伐証-はんもんいんりゅうのとうばつしょう-魔法防御力+100、弓装備クラスにセット時追加で攻撃力+100、魔法防御力+30-まほうぼうぎょ-ゆみ-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1158.png"
        alt="捕獲！自信に満ちた女勇者-ほかくじしんにみちたおんなゆうしゃ-セット時、全ウォリアー系クラスの攻撃力+15%\r\n自信に満ちた女勇者をトークンとして使役可能\r\n(元々トークン所持している場合は無効)-とーくん-へんせいじ-こうげきりょく-ウォリアー-うぉりあー"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1159.png"
        alt="捕獲！二丁使いの女海賊-ほかくにちょうづかいのおんなかいぞく-セット時、全スナイパー系クラスの攻撃速度が15%増加\r\n二丁使いの女海賊をトークンとして使役可能\r\n(元々トークン所持している場合は無効)-とーくん-へんせいじ-こうげきそくど-すないぱー"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1160.png"
        alt="豪華絢爛-ごうかけんらん-攻撃力+90、扇装備クラスにセット時追加で射程+10-こうげきりょく-しゃてい-せんす-うちわ-おうぎ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1161.png"
        alt="再出撃時間+出撃コスト減少-さいしゅつげんじかんたんしゅくしゅつげきこすとげんしょう-再出撃までの時間を45%短縮\r\n出撃コスト-1"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1162.png"
        alt="攻撃強化+HP強化-こうげききょうかえいちぴーきょうか-攻撃力+17%、HP+20%-こうげきりょく-えいちぴー"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1163.png"
        alt="戦意継承-せんいけいしょう-再出撃までの時間を40%短縮(重複不可)\r\n自身の死亡時、味方全員の攻撃力を10秒間100%上昇させる-さいしゅつげきたんしゅく-しぼう-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1164.png"
        alt="パートナーチアー-ぱーとなーちあー-配置中の自身が使役しているトークンの\r\n攻撃力と物理防御力+60%-こうげきりょく-とーくん-ぶつりぼうぎょ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1165.png"
        alt="攻撃強化+攻撃待機短縮-こうげききょうかこうげきたいきたんしゅく-攻撃力+17%、攻撃後の待機時間を20%短縮-こうげきりょく-たいきじかん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1166.png"
        alt="ムッツリ妄想フルパワー-むっつりもうそうふるぱわー-物理防御+85、魔法防御+85\r\n鈍器装備クラスにセット時追加で\r\n攻撃力+19%、クリティカル率+19%-ぶつりぼうぎょ-まほうぼうぎょ-こうげきりょく-くりてぃかるりつ-どんき-こん棒-こんぼう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1167.png"
        alt="攻撃強化+底力(攻撃)-こうげききょうかそこぢからこうげき-攻撃力+17%、HP減少量に応じて攻撃力が上昇する(最大40%)-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1168.png"
        alt="2nd Anniversaryの恩寵-せかんどあにばーさりーのおんちょう-攻撃力+22%\r\nクリティカル率+22%\r\nクリティカルダメージ+22%-こうげきりょく-くりてぃかるりつ-くりてぃかるだめーじ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1169.png"
        alt="魔法攻撃回避 IV-まほうこうげきかいひよん-35%の確率で魔法攻撃を回避-まほうこうげきかいひ-まほうかいひ"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1170.png"
        alt="生命力吸収 IV-せいめいりょくきゅうしゅうよん-攻撃時、HPが最大値の4%回復-こうげきじかいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1171.png"
        alt="パワードバリア-ぱわーどばりあ-スキル発動時、自身のHPを25%回復し、自身に戦闘前の攻撃力の250%のバリアを付与-かいふく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1172.png"
        alt="鉄壁の守り-てっぺきのまもり-与ダメージが30%減少するが、自身が受ける物理魔法ダメージが30%減少-よだめーじ-ぶつりだめーじげんしょう-まほうだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1173.png"
        alt="ファイアエクステンド-ふぁいあえくすてんど-編成時火属性モンスター娘のHPと攻撃力+10%-へんせいじ-ひぞくせい-こうげきりょく"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1174.png"
        alt="ミノタウロスソウル-みのたうろすそうる-ブロック中の敵への与ダメージ1.2倍\r\nミノタウロス（原種）をトークンとして使役可能-ぶろっくちゅう-ぶろっくじ-よだめーじ-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1175.png"
        alt="被検体R13-ひけんたいあーるいちさん-ひけんたいあーるじゅうさん-【改造リザードマン娘】サウラをトークンとして使役可能\r\n（元々トークン所持している場合は無効）-とーくん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1176.png"
        alt="暗部の聖衣-あんぶのせいい-HP+18%\r\nヒーラー系クラスにセット時、追加で物理と魔法ダメージを5%軽減-えいちぴー-ひーらー-ぶつりだめーじげんしょう-まほうだめーじげんしょう"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
        <img class="subskill-select-img-2"
        src="../../img/subskill-icons/subskill_1177.png"
        alt="愛造暴玩の討伐証-あいぞうぼうがんのとうばつしょう-物理ダメージを10％減少\r\nガーディアン系クラスにセット時追加で物理ダメージを20％減少-ぶつりだめーじげんしょう-がーでぃあん"
        onclick="subskillSearchSelect(this.src,'2');subskillSearchClose();allDPS();">
    </div>
</div>
`);